name: 'first_cpu-32x32'
device: cpu
training:
  threads: 8
  batch_size: 8192
  input: '.\input_sample\'
  validation: '.\validation_sample\'
  output: '.\training\'
  steps: 100
  learning_rate:
    - 0.01
    - 0.001
    - 0.0001
  learning_rate_bounds:
    - 50
    - 80
model:
  type: 0
  dense:
     - 32
     - 32
     - 1