name: 'adagrad_b16384_256_32_s9'
device: cuda:0
threads: 8
training:
  batch_size: 16384
  input: '.\input_sample\'
  validation: '.\validation_sample\'
  output: '.\training\'
  epochs: 200
  learning_rate: 0.05
model:
  type: 0
  dense:
     - 256
     - 32
     - 1