name: 'adagrad_b65536_128x32x32'
device: cuda:0
threads: 12
training:
  batch_size: 65536
  input: '.\input_sample\'
  validation: '.\validation_sample\'
  output: '.\training\'
  epochs: 1000
  learning_rate: 0.05
model:
  type: 0
  dense:
     - 128
     - 32
     - 32
     - 1