name: 'adam_b65535_32x32'
device: cuda:0
training:
  batch_size: 65535
  input: '.\input_sample\'
  validation: '.\validation_sample\'
  output: '.\training\'
  steps: 300
  learning_rate: 0.05
model:
  type: 0
  dense:
     - 32
     - 32
     - 1